const mongoose = require('mongoose');

const themedCompilationSchema = new mongoose.Schema({
  title: {
    type: String,
    required: true,
    trim: true,
  },
  tagGroup: {
    type: String,
    required: true,
    lowercase: true,
    trim: true,
  },
  lessons: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Lesson',
    validate: {
      validator: function(arr) { return arr.length >= 4 && arr.length <= 6; },
      message: 'Compilations must have 4–6 lessons',
    },
  }],
  coverImageUrl: String,
  grade: {
    type: String,
    enum: ['LKG', 'UKG', 'both'],
    default: 'both',
  },
  autoGenerated: { type: Boolean, default: false },
  published: { type: Boolean, default: false },
}, { timestamps: true });

module.exports = mongoose.model('ThemedCompilation', themedCompilationSchema);
