export type Grade = 'LKG' | 'UKG';

export type VideoFormat =
  | 'sing_along' | 'phonics_song' | 'number_song' | 'moral_story' | 'bedtime_story'
  | 'action_dance' | 'yoga_stretch' | 'good_habits' | 'festival_special' | 'point_and_learn'
  | 'emotion_song' | 'original_song' | 'recap_song' | 'celebration_video' | 'themed_compilation';

export type LessonStatus = 'draft' | 'generating' | 'ready' | 'published' | 'archived';
export type ActivityType = 'quiz' | 'flashcard' | 'story' | 'matching' | 'phonics' | 'fill_blank' | 'memory' | 'spell';
export type AchievementType = 'badge' | 'trophy' | 'certificate';

export interface Subject {
  _id: string; name: string; slug: string; icon: string; color: string; grades: Grade[];
}

export interface Lesson {
  _id: string; title: string; grade: Grade; subject: Subject; videoFormat: VideoFormat;
  videoUrl?: string; thumbnailUrl?: string; scriptText?: string; durationSeconds?: number;
  tags: string[]; status: LessonStatus; viewCount: number; publishedAt?: string; createdAt: string;
}

export interface ThemedCompilation {
  _id: string; title: string; tagGroup: string; lessons: Lesson[];
  coverImageUrl?: string; grade: Grade | 'both'; autoGenerated: boolean;
}

export interface ContentCalendarSuggestion {
  _id: string; weekOf: string; region: string;
  suggestedMix: Array<{ videoFormat: VideoFormat; count: number; rationale?: string }>;
  upcomingFestival?: { name: string; date: string; suggestedFormats: VideoFormat[] };
  status: 'pending' | 'acknowledged' | 'acted';
}

// ── Activity ─────────────────────────────────────────────────────────────────

export interface QuizQuestion {
  question: string; options: string[]; correct: number; emoji?: string; explanation?: string;
}
export interface Flashcard {
  front: string; back: string; emoji?: string; example?: string;
}
export interface MatchPair {
  word: string; emoji: string;
}
export interface StoryPage {
  text: string; emoji?: string; bg?: string;
}
export interface MemoryCard {
  id: string; emoji: string; pairId: string;
}
export interface SpellWord {
  word: string; emoji: string; hint?: string;
}
export interface ActivityContent {
  questions?: QuizQuestion[];
  cards?: Flashcard[];
  pairs?: MatchPair[];
  pages?: StoryPage[];
  words?: string[];
  memoryCards?: MemoryCard[];
  spellWords?: SpellWord[];
}
export interface Activity {
  _id: string; lesson: string; type: ActivityType; title?: string;
  grade: Grade; difficulty: 'easy' | 'medium' | 'hard';
  xpReward: number; coinsReward: number; status: 'draft' | 'published';
  content: ActivityContent; createdAt: string;
}

// ── Achievement ───────────────────────────────────────────────────────────────

export interface Achievement {
  _id: string; name: string; icon: string; description?: string;
  type: AchievementType; metric: string; value: number; xpReward: number; order: number;
  earned?: boolean; earnedAt?: string | null;
}

// ── Child ─────────────────────────────────────────────────────────────────────

export interface Child {
  _id: string; name: string; grade: Grade; avatar: string;
  badges: Array<{ name: string; earnedAt: string; videoFormat: VideoFormat }>;
  streaks: { current: number; longest: number; lastActivityDate?: string };
  xp: number; coins: number; level: number;
  watchHistory: Array<{
    lesson: string | { _id: string; title?: string; videoFormat?: string; thumbnailUrl?: string };
    watchedAt: string; completedPercent: number;
  }>;
  activityHistory: Array<{
    activity: string; lesson: string; activityType: ActivityType;
    score: number; xpEarned: number; coinsEarned: number; completedAt: string;
  }>;
  achievements: Array<{ achievement: string | Achievement; earnedAt: string }>;
}

export interface User {
  id: string; name: string; email: string;
  role: 'founder' | 'admin' | 'staff' | 'parent';
}

// ── Labels & Icons ────────────────────────────────────────────────────────────

export const VIDEO_FORMAT_LABELS: Record<VideoFormat, string> = {
  sing_along: 'Sing-Along Rhyme', phonics_song: 'Phonics Song', number_song: 'Number Song',
  moral_story: 'Moral Story', bedtime_story: 'Bedtime Story', action_dance: 'Action / Dance-Along',
  yoga_stretch: 'Yoga & Stretch', good_habits: 'Good Habits', festival_special: 'Festival Special',
  point_and_learn: 'Point & Learn', emotion_song: 'Emotion & Calm-Down Song', original_song: 'Original Song',
  recap_song: 'Recap Song', celebration_video: 'Celebration Video', themed_compilation: 'Themed Compilation',
};

export const VIDEO_FORMAT_ICONS: Record<VideoFormat, string> = {
  sing_along: '🎤', phonics_song: '🔤', number_song: '🔢', moral_story: '📖', bedtime_story: '🌙',
  action_dance: '💃', yoga_stretch: '🧘', good_habits: '✨', festival_special: '🎉',
  point_and_learn: '👆', emotion_song: '😊', original_song: '🎵', recap_song: '🔁',
  celebration_video: '🏆', themed_compilation: '📋',
};

export const ACTIVITY_ICONS: Record<ActivityType, string> = {
  quiz: '❓', flashcard: '🃏', story: '📖', matching: '🎯', phonics: '🔤', fill_blank: '✏️', memory: '🧠', spell: '✍️',
};
export const ACTIVITY_LABELS: Record<ActivityType, string> = {
  quiz: 'Quiz', flashcard: 'Flashcards', story: 'Story', matching: 'Match It', phonics: 'Phonics', fill_blank: 'Fill in Blank', memory: 'Memory', spell: 'Spell It',
};
