export type Grade = 'LKG' | 'UKG';

export type VideoFormat =
  | 'sing_along'
  | 'phonics_song'
  | 'number_song'
  | 'moral_story'
  | 'bedtime_story'
  | 'action_dance'
  | 'yoga_stretch'
  | 'good_habits'
  | 'festival_special'
  | 'point_and_learn'
  | 'emotion_song'
  | 'original_song'
  | 'recap_song'
  | 'celebration_video'
  | 'themed_compilation';

export type LessonStatus = 'draft' | 'generating' | 'ready' | 'published' | 'archived';

export interface Subject {
  _id: string;
  name: string;
  slug: string;
  icon: string;
  color: string;
  grades: Grade[];
}

export interface Lesson {
  _id: string;
  title: string;
  grade: Grade;
  subject: Subject;
  videoFormat: VideoFormat;
  videoUrl?: string;
  thumbnailUrl?: string;
  scriptText?: string;
  durationSeconds?: number;
  tags: string[];
  status: LessonStatus;
  viewCount: number;
  publishedAt?: string;
  createdAt: string;
}

export interface ThemedCompilation {
  _id: string;
  title: string;
  tagGroup: string;
  lessons: Lesson[];
  coverImageUrl?: string;
  grade: Grade | 'both';
  autoGenerated: boolean;
}

export interface ContentCalendarSuggestion {
  _id: string;
  weekOf: string;
  region: string;
  suggestedMix: Array<{ videoFormat: VideoFormat; count: number; rationale?: string }>;
  upcomingFestival?: { name: string; date: string; suggestedFormats: VideoFormat[] };
  status: 'pending' | 'acknowledged' | 'acted';
}

export interface Child {
  _id: string;
  name: string;
  grade: Grade;
  avatar: string;
  badges: Array<{ name: string; earnedAt: string; videoFormat: VideoFormat }>;
  streaks: { current: number; longest: number; lastActivityDate?: string };
  watchHistory: Array<{
    lesson: string | { _id: string; title?: string };
    watchedAt?: string;
    completedPercent?: number;
  }>;
}

export interface User {
  id: string;
  name: string;
  email: string;
  role: 'founder' | 'admin' | 'staff' | 'parent';
}

export const VIDEO_FORMAT_LABELS: Record<VideoFormat, string> = {
  sing_along: 'Sing-Along Rhyme',
  phonics_song: 'Phonics Song',
  number_song: 'Number Song',
  moral_story: 'Moral Story',
  bedtime_story: 'Bedtime Story',
  action_dance: 'Action / Dance-Along',
  yoga_stretch: 'Yoga & Stretch',
  good_habits: 'Good Habits',
  festival_special: 'Festival Special',
  point_and_learn: 'Point & Learn',
  emotion_song: 'Emotion & Calm-Down Song',
  original_song: 'Original Song',
  recap_song: 'Recap Song',
  celebration_video: 'Celebration Video',
  themed_compilation: 'Themed Compilation',
};

export const VIDEO_FORMAT_ICONS: Record<VideoFormat, string> = {
  sing_along: '🎤',
  phonics_song: '🔤',
  number_song: '🔢',
  moral_story: '📖',
  bedtime_story: '🌙',
  action_dance: '💃',
  yoga_stretch: '🧘',
  good_habits: '✨',
  festival_special: '🎉',
  point_and_learn: '👆',
  emotion_song: '😊',
  original_song: '🎵',
  recap_song: '🔁',
  celebration_video: '🏆',
  themed_compilation: '📋',
};
