const router = require('express').Router();
const jwt = require('jsonwebtoken');
const ThemedCompilation = require('../models/ThemedCompilation');
const Lesson = require('../models/Lesson');
const { protect, staffOrAbove } = require('../middleware/auth');

function optionalAuth(req, res, next) {
  const token = req.headers.authorization?.split(' ')[1];
  if (!token) return next();
  try { req.user = jwt.verify(token, process.env.JWT_SECRET); } catch { /* ignore */ }
  next();
}

router.get('/', optionalAuth, async (req, res, next) => {
  try {
    const { grade, all } = req.query;
    const isStaff = req.user && ['staff', 'admin', 'founder'].includes(req.user.role);
    const filter = (all === 'true' && isStaff) ? {} : { published: true };
    if (grade) filter.grade = { $in: [grade, 'both'] };
    const compilations = await ThemedCompilation.find(filter)
      .populate('lessons', 'title videoFormat thumbnailUrl durationSeconds')
      .sort({ createdAt: -1 });
    res.json({ success: true, data: compilations });
  } catch (err) { next(err); }
});

router.get('/:id', async (req, res, next) => {
  try {
    const comp = await ThemedCompilation.findById(req.params.id).populate({ path: 'lessons', populate: { path: 'subject', select: 'name icon' } });
    if (!comp) return res.status(404).json({ success: false, message: 'Compilation not found' });
    res.json({ success: true, data: comp });
  } catch (err) { next(err); }
});

router.post('/', protect, staffOrAbove, async (req, res, next) => {
  try {
    const comp = await ThemedCompilation.create(req.body);
    res.status(201).json({ success: true, data: comp });
  } catch (err) { next(err); }
});

// Auto-generate compilations for tags that have 4+ lessons
router.post('/auto-generate', protect, staffOrAbove, async (req, res, next) => {
  try {
    const pipeline = [
      { $match: { status: 'published' } },
      { $unwind: '$tags' },
      { $group: { _id: '$tags', lessons: { $push: '$_id' }, count: { $sum: 1 } } },
      { $match: { count: { $gte: 4 } } },
    ];
    const tagGroups = await Lesson.aggregate(pipeline);
    const created = [];
    for (const group of tagGroups) {
      const existing = await ThemedCompilation.findOne({ tagGroup: group._id });
      if (!existing) {
        const lessons = group.lessons.slice(0, 6);
        const comp = await ThemedCompilation.create({
          title: `${group._id.charAt(0).toUpperCase() + group._id.slice(1)} Collection`,
          tagGroup: group._id,
          lessons,
          autoGenerated: true,
          published: true,
        });
        created.push(comp);
      }
    }
    res.json({ success: true, created: created.length, data: created });
  } catch (err) { next(err); }
});

router.patch('/:id/publish', protect, staffOrAbove, async (req, res, next) => {
  try {
    const comp = await ThemedCompilation.findById(req.params.id);
    if (!comp) return res.status(404).json({ success: false, message: 'Compilation not found' });
    comp.published = !comp.published;
    await comp.save();
    res.json({ success: true, data: comp });
  } catch (err) { next(err); }
});

router.delete('/:id', protect, staffOrAbove, async (req, res, next) => {
  try {
    await ThemedCompilation.findByIdAndDelete(req.params.id);
    res.json({ success: true, message: 'Compilation deleted' });
  } catch (err) { next(err); }
});

router.put('/:id', protect, staffOrAbove, async (req, res, next) => {
  try {
    const comp = await ThemedCompilation.findByIdAndUpdate(req.params.id, req.body, { new: true, runValidators: true });
    if (!comp) return res.status(404).json({ success: false, message: 'Compilation not found' });
    res.json({ success: true, data: comp });
  } catch (err) { next(err); }
});

module.exports = router;
