'use client';

import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { compilationsApi, lessonsApi } from '@/lib/api';
import { useToast } from '@/context/ToastContext';
import type { Lesson, ThemedCompilation } from '@/types';
import { VIDEO_FORMAT_ICONS, VIDEO_FORMAT_LABELS } from '@/types';

type CompRecord = ThemedCompilation & { published: boolean; autoGenerated: boolean; tagGroup: string };

interface EditState {
  comp: CompRecord;
  lessonIds: string[];
}

export default function CompilationsPage() {
  const [compilations, setCompilations] = useState<CompRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [toggling, setToggling] = useState<string | null>(null);
  const [deleting, setDeleting] = useState<string | null>(null);
  const [edit, setEdit] = useState<EditState | null>(null);
  const [allLessons, setAllLessons] = useState<Lesson[]>([]);
  const [lessonSearch, setLessonSearch] = useState('');
  const [saving, setSaving] = useState(false);
  const searchRef = useRef<HTMLInputElement>(null);
  const { toast } = useToast();

  async function load() {
    try {
      const res = await compilationsApi.listAll() as { data: CompRecord[] };
      setCompilations(res.data ?? []);
    } catch {
      toast('Failed to load compilations', 'error');
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => { load(); }, []); // eslint-disable-line react-hooks/exhaustive-deps

  async function openEdit(comp: CompRecord) {
    const currentIds = comp.lessons.map(l =>
      typeof l === 'object' ? (l as Lesson)._id : l as unknown as string
    );
    setEdit({ comp, lessonIds: currentIds });
    setLessonSearch('');
    if (allLessons.length === 0) {
      try {
        // Fetch both published and ready lessons for the search pool
        const [pubRes, readyRes] = await Promise.all([
          lessonsApi.list({ status: 'published', limit: '200' }) as Promise<{ data: Lesson[] }>,
          lessonsApi.list({ status: 'ready', limit: '100' }) as Promise<{ data: Lesson[] }>,
        ]);
        const combined = [...(pubRes.data ?? []), ...(readyRes.data ?? [])];
        const unique = combined.filter((l, i, arr) => arr.findIndex(x => x._id === l._id) === i);
        setAllLessons(unique);
      } catch {}
    }
    setTimeout(() => searchRef.current?.focus(), 50);
  }

  async function handleSaveEdit() {
    if (!edit) return;
    setSaving(true);
    try {
      await compilationsApi.update(edit.comp._id, { lessons: edit.lessonIds });
      toast('Playlist updated ✅');
      setEdit(null);
      load();
    } catch {
      toast('Failed to save', 'error');
    } finally {
      setSaving(false);
    }
  }

  async function handleToggle(id: string, currentlyPublished: boolean) {
    setToggling(id);
    try {
      await compilationsApi.togglePublish(id);
      setCompilations(prev => prev.map(c => c._id === id ? { ...c, published: !currentlyPublished } : c));
      toast(currentlyPublished ? 'Playlist unpublished' : 'Playlist published ✅');
    } catch {
      toast('Failed to update', 'error');
    } finally {
      setToggling(null);
    }
  }

  async function handleDelete(id: string, title: string) {
    if (!confirm(`Delete "${title}"? This cannot be undone.`)) return;
    setDeleting(id);
    try {
      await compilationsApi.delete(id);
      setCompilations(prev => prev.filter(c => c._id !== id));
      toast('Playlist deleted');
    } catch {
      toast('Failed to delete', 'error');
    } finally {
      setDeleting(null);
    }
  }

  async function handleAutoGenerate() {
    try {
      const res = await compilationsApi.autoGenerate() as { created?: number };
      const count = res.created ?? 0;
      toast(count > 0 ? `${count} new playlist${count > 1 ? 's' : ''} created 🎬` : 'No new playlists — need 4+ lessons with the same tag', count > 0 ? 'success' : 'info');
      if (count > 0) load();
    } catch {
      toast('Auto-generate failed', 'error');
    }
  }

  // Lessons currently in the edit draft — look in allLessons first, then fall back to the
  // already-populated comp.lessons (covers non-published statuses like "ready")
  const editLessons = edit
    ? edit.lessonIds.map(id => {
        const fromAll = allLessons.find(l => l._id === id);
        if (fromAll) return fromAll;
        const fromComp = edit.comp.lessons.find(l => typeof l === 'object' && (l as Lesson)._id === id);
        return fromComp ? (fromComp as unknown as Lesson) : null;
      }).filter(Boolean) as Lesson[]
    : [];

  // Lessons not yet added, filtered by search
  const searchLower = lessonSearch.toLowerCase();
  const available = allLessons.filter(
    l => !edit?.lessonIds.includes(l._id) &&
      (lessonSearch === '' || l.title.toLowerCase().includes(searchLower) || (l.tags ?? []).some(t => t.toLowerCase().includes(searchLower)))
  ).slice(0, 20);

  return (
    <div className="max-w-4xl mx-auto px-4 py-8">
      {/* Header */}
      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="text-2xl text-brand-pink">Playlists</h1>
          <p className="text-sm text-gray-400 font-body mt-0.5">Manage themed video compilations for children</p>
        </div>
        <button
          onClick={handleAutoGenerate}
          className="px-4 py-2 bg-brand-purple text-white rounded-xl text-sm font-bold hover:bg-purple-700 transition-colors"
        >
          ✨ Auto-Generate
        </button>
      </div>

      {loading ? (
        <div className="flex items-center justify-center py-20">
          <div className="text-5xl animate-bounce">📋</div>
        </div>
      ) : compilations.length === 0 ? (
        <div className="bg-white rounded-3xl p-12 text-center card-shadow">
          <div className="text-6xl mb-4">📋</div>
          <h2 className="text-xl font-bold text-gray-700 mb-2">No playlists yet</h2>
          <p className="text-gray-400 font-body text-sm mb-6">
            Playlists are auto-generated when 4+ lessons share the same tag.<br />
            Tag your lessons consistently, then click Auto-Generate.
          </p>
          <button
            onClick={handleAutoGenerate}
            className="px-6 py-3 bg-brand-purple text-white rounded-2xl font-bold hover:bg-purple-700 transition-colors"
          >
            ✨ Auto-Generate Now
          </button>
        </div>
      ) : (
        <div className="space-y-3">
          {compilations.map(comp => (
            <div key={comp._id} className="bg-white rounded-3xl p-5 card-shadow flex items-center gap-4">
              <div className="w-12 h-12 rounded-2xl bg-pink-50 flex items-center justify-center text-2xl flex-shrink-0">
                📋
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 flex-wrap">
                  <p className="font-bold text-gray-800">{comp.title}</p>
                  {comp.autoGenerated && (
                    <span className="px-2 py-0.5 bg-purple-50 text-purple-600 text-xs font-bold rounded-full">auto</span>
                  )}
                  <span className={`px-2 py-0.5 text-xs font-bold rounded-full ${comp.published ? 'bg-green-50 text-green-600' : 'bg-gray-100 text-gray-500'}`}>
                    {comp.published ? 'published' : 'draft'}
                  </span>
                </div>
                <p className="text-xs text-gray-400 font-body mt-0.5">
                  {comp.lessons.length} videos · tag: #{comp.tagGroup} · grade: {comp.grade}
                </p>
              </div>
              <div className="flex items-center gap-2 flex-shrink-0">
                <button
                  onClick={() => openEdit(comp)}
                  className="px-3 py-1.5 bg-blue-50 text-blue-600 rounded-xl text-xs font-bold hover:bg-blue-100 transition-colors">
                  ✏️ Edit
                </button>
                <Link href={`/playlist/${comp._id}`} target="_blank"
                  className="px-3 py-1.5 bg-gray-50 text-gray-600 rounded-xl text-xs font-bold hover:bg-gray-100 transition-colors">
                  👁 Preview
                </Link>
                <button
                  onClick={() => handleToggle(comp._id, comp.published)}
                  disabled={toggling === comp._id}
                  className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-colors disabled:opacity-50 ${comp.published ? 'bg-yellow-50 text-yellow-600 hover:bg-yellow-100' : 'bg-green-50 text-green-600 hover:bg-green-100'}`}
                >
                  {toggling === comp._id ? '⏳' : comp.published ? 'Unpublish' : 'Publish'}
                </button>
                <button
                  onClick={() => handleDelete(comp._id, comp.title)}
                  disabled={deleting === comp._id}
                  className="px-3 py-1.5 bg-red-50 text-red-500 rounded-xl text-xs font-bold hover:bg-red-100 transition-colors disabled:opacity-50"
                >
                  {deleting === comp._id ? '⏳' : '🗑'}
                </button>
              </div>
            </div>
          ))}
        </div>
      )}

      <div className="mt-6 p-4 bg-yellow-50 rounded-2xl text-xs text-yellow-700 font-body">
        💡 <strong>Tip:</strong> Tag lessons consistently (e.g. <code className="bg-yellow-100 px-1 rounded">animals</code>, <code className="bg-yellow-100 px-1 rounded">festival-diwali</code>).
        When 4+ lessons share a tag, Auto-Generate creates a playlist automatically. Use ✏️ Edit to manually add or reorder videos.
      </div>

      {/* Edit Modal */}
      {edit && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
          <div className="bg-white rounded-3xl w-full max-w-2xl max-h-[90vh] flex flex-col shadow-2xl">
            {/* Modal header */}
            <div className="px-6 pt-6 pb-4 border-b border-gray-100 flex items-center justify-between flex-shrink-0">
              <div>
                <h2 className="text-xl font-bold text-gray-800">{edit.comp.title}</h2>
                <p className="text-xs text-gray-400 font-body mt-0.5">{edit.lessonIds.length} video{edit.lessonIds.length !== 1 ? 's' : ''} in this playlist</p>
              </div>
              <button onClick={() => setEdit(null)} className="text-gray-400 hover:text-gray-600 text-2xl leading-none">✕</button>
            </div>

            <div className="flex-1 overflow-y-auto p-6 space-y-5 min-h-0">
              {/* Current lessons */}
              <div>
                <h3 className="text-sm font-semibold text-gray-500 mb-2">Current videos (drag to reorder)</h3>
                {editLessons.length === 0 ? (
                  <p className="text-sm text-gray-400 font-body">No videos yet — add some below.</p>
                ) : (
                  <div className="space-y-2">
                    {editLessons.map((l, idx) => (
                      <div key={l._id} className="flex items-center gap-3 p-3 bg-gray-50 rounded-2xl group">
                        <span className="text-xs font-bold text-gray-400 w-5 text-center">{idx + 1}</span>
                        <span className="text-lg">{VIDEO_FORMAT_ICONS[l.videoFormat]}</span>
                        <div className="flex-1 min-w-0">
                          <p className="text-sm font-semibold text-gray-700 truncate">{l.title}</p>
                          <p className="text-xs text-gray-400 font-body">{VIDEO_FORMAT_LABELS[l.videoFormat]}</p>
                        </div>
                        <div className="flex gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                          {idx > 0 && (
                            <button
                              onClick={() => {
                                const ids = [...edit.lessonIds];
                                [ids[idx - 1], ids[idx]] = [ids[idx], ids[idx - 1]];
                                setEdit(e => e ? { ...e, lessonIds: ids } : e);
                              }}
                              className="w-6 h-6 bg-gray-200 rounded-lg text-xs hover:bg-gray-300 transition-colors">↑</button>
                          )}
                          {idx < editLessons.length - 1 && (
                            <button
                              onClick={() => {
                                const ids = [...edit.lessonIds];
                                [ids[idx], ids[idx + 1]] = [ids[idx + 1], ids[idx]];
                                setEdit(e => e ? { ...e, lessonIds: ids } : e);
                              }}
                              className="w-6 h-6 bg-gray-200 rounded-lg text-xs hover:bg-gray-300 transition-colors">↓</button>
                          )}
                          <button
                            onClick={() => setEdit(e => e ? { ...e, lessonIds: e.lessonIds.filter(id => id !== l._id) } : e)}
                            className="w-6 h-6 bg-red-100 text-red-500 rounded-lg text-xs hover:bg-red-200 transition-colors">✕</button>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Add lessons */}
              <div>
                <h3 className="text-sm font-semibold text-gray-500 mb-2">Add videos</h3>
                <input
                  ref={searchRef}
                  value={lessonSearch}
                  onChange={e => setLessonSearch(e.target.value)}
                  placeholder="Search by title or tag…"
                  className="w-full border-2 border-gray-200 rounded-2xl px-4 py-2.5 text-sm font-body focus:border-brand-pink outline-none transition-colors mb-3"
                />
                {available.length === 0 ? (
                  <p className="text-sm text-gray-400 font-body text-center py-3">
                    {lessonSearch ? 'No matching published lessons found.' : 'All published lessons are already in this playlist.'}
                  </p>
                ) : (
                  <div className="space-y-1.5">
                    {available.map(l => (
                      <button
                        key={l._id}
                        onClick={() => setEdit(e => e ? { ...e, lessonIds: [...e.lessonIds, l._id] } : e)}
                        className="w-full flex items-center gap-3 p-3 rounded-2xl hover:bg-pink-50 transition-colors text-left border-2 border-transparent hover:border-brand-pink/20">
                        <span className="text-lg">{VIDEO_FORMAT_ICONS[l.videoFormat]}</span>
                        <div className="flex-1 min-w-0">
                          <p className="text-sm font-semibold text-gray-700 truncate">{l.title}</p>
                          <p className="text-xs text-gray-400 font-body">{VIDEO_FORMAT_LABELS[l.videoFormat]} · {l.grade}</p>
                        </div>
                        <span className="text-brand-pink text-sm font-bold flex-shrink-0">+ Add</span>
                      </button>
                    ))}
                  </div>
                )}
              </div>
            </div>

            {/* Modal footer */}
            <div className="px-6 py-4 border-t border-gray-100 flex justify-end gap-3 flex-shrink-0">
              <button onClick={() => setEdit(null)} className="px-5 py-2.5 text-sm font-bold text-gray-500 hover:text-gray-700 transition-colors">
                Cancel
              </button>
              <button
                onClick={handleSaveEdit}
                disabled={saving}
                className="px-6 py-2.5 bg-brand-pink text-white rounded-2xl text-sm font-bold hover:bg-pink-600 transition-colors disabled:opacity-50">
                {saving ? '⏳ Saving…' : 'Save Playlist'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
